# Generated by Django 4.2.7 on 2023-11-20 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidatedirectory',
            options={'managed': False},
        ),
    ]
