# Generated by Django 4.2.7 on 2023-11-21 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requ', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='candidatedirectory',
            constraint=models.UniqueConstraint(fields=('first_name', 'last_name'), name='full_name'),
        ),
        migrations.AlterModelTable(
            name='candidatedirectory',
            table='CandidateDirectory',
        ),
    ]
