# Generated by Django 4.2.7 on 2023-11-21 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0002_alter_candidatedirectory_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='candidatedirectory',
            table='CandidateDirectory',
        ),
    ]
